version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    networks:
      - todoapp
networks:
  todoapp:
    driver: bridge